steps:
- env
- python3.7 -m venv .venv
- ls -la .venv/bin
- .venv/bin/python -m ensurepip
- .venv/bin/python -m pip install ./pydoc-markdown
- ls -la .venv/bin
- .venv/bin/pydoc-markdown --build --site-dir $SITE_DIR -vv
