steps:
- env
- find / -type f -name python3.7 2>/dev/null || true
- /home/docs/.pyenv/shims/python3.7 -m virtualenv .venv
- ls -la .venv/bin
- .venv/bin/python -m ensurepip
- .venv/bin/python -m pip install ./pydoc-markdown
- ls -la .venv/bin
- .venv/bin/pydoc-markdown --build --site-dir $SITE_DIR -vv
