steps:
- env
- ls -la /usr/bin
- ls -la /usr/sbin
- /usr/bin/python3.7 -m virtualenv .venv
- ls -la .venv/bin
- .venv/bin/python -m ensurepip
- .venv/bin/python -m pip install ./pydoc-markdown
- ls -la .venv/bin
- .venv/bin/pydoc-markdown --build --site-dir $SITE_DIR -vv
